---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: default
spec:
  bgpInstances:
    - name: cilium
      localASN: 64512
      peers:
        - name: node
          peerASN: 64513
          peerAddress: 127.0.0.1
          peerConfigRef:
            name: default-peer
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: default-peer
spec:
  timers:
    connectRetryTimeSeconds: 5
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels: {}
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: pods-and-services
spec:
  advertisements:
    # required for reverse paths from the router, as we disabled masquerading
    - advertisementType: CiliumPodIPPool
      selector:
        matchLabels: {}
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels: {}
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
spec:
  blocks:
    # 10.112.10.1-10.112.10.99 is for automatically allocated IPs
    # 10.112.10.100-10.112.10.199 is for manually allocated IPs
    # 10.112.10.200-10.112.10.255 is for other services in the region
    - start: "10.112.10.1"
      stop: "10.112.10.199"
  serviceSelector:
    # change it if we add more IP pools
    matchLabels: {}
