---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tillycode/homelab-v2.git
    targetRevision: main
    path: k8s/whoami
  destination:
    server: https://kubernetes.default.svc
