[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "scripts"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["pyyaml~=6.0"]

[project.scripts]
pkgmgr = "scripts.pkgmgr:main"
secretmgr = "scripts.secretmgr:main"
flat-flake = "scripts.flat_flake:main"

[tool.uv.build-backend]
module-root = ""

[tool.pyright]
typeCheckingMode = "strict"
