domain: "szp.io szp15.com"
watchedResources:
  - HTTPRoute
  - TLSRoute
  - GRPCRoute

service:
  annotations:
    lbipam.cilium.io/ips: 10.112.10.10
  externalTrafficPolicy: Local

replicaCount: 2

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: internal-dns
            app.kubernetes.io/name: k8s-gateway
        topologyKey: kubernetes.io/hostname
