---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-http-route
  namespace: argocd
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: gateway
      sectionName: https
  hostnames:
    - argocd.k8s.szp.io
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: argocd-server
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: argocd-grpc-route
  namespace: argocd
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: gateway
      sectionName: https
  hostnames:
    - argocd.k8s.szp.io
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: argocd-server
          port: 443
      matches:
        - headers:
            - name: Content-Type
              type: RegularExpression
              value: "^application/grpc.*$"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gateway-gateway
  namespace: argocd
specs:
  - description: "Allow traffic from gateway to argocd"
    endpointSelector:
      matchLabels:
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/name: argocd-server
    ingress:
      - fromEntities:
          - ingress
