---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: gateway
      sectionName: https
  hostnames:
    - sealed-secrets.k8s.szp.io
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: sealed-secrets
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gateway-gateway
  namespace: sealed-secrets
specs:
  - description: "Allow traffic from gateway to sealed-secrets"
    endpointSelector:
      matchLabels:
        app.kubernetes.io/instance: sealed-secrets
        app.kubernetes.io/name: sealed-secrets
    ingress:
      - fromEntities:
          - ingress
