# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/ceph.rook.io/cephcluster_v1.json
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.3
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
  mgr:
    count: 2
  dashboard:
    enabled: true
  storage:
    nodes:
      - name: hasee01
        devices:
          - name: /dev/pool/ceph01
          - name: /dev/pool/ceph02
      - name: hasee02
        devices:
          - name: /dev/pool/ceph01
          - name: /dev/pool/ceph02
      - name: hasee03
        devices:
          - name: /dev/pool/ceph01
          - name: /dev/pool/ceph02
