---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-osd-env-override
data:
  # see https://github.com/rook/rook/issues/16841
  #
  # Default ceph image PATH:
  # /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  # Default NixOS PATH (user-specific dirs omitted)
  # /run/wrappers/bin:/nix/profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
  PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/run/wrappers/bin:/nix/profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"
