apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
  - cluster.yaml
  - configmaps.yaml
  - https://raw.githubusercontent.com/rook/rook/refs/heads/release-1.9/deploy/examples/toolbox.yaml
  - block.yaml
  - filesystem.yaml
  - object.yaml
